export const enum ColorPalette {
    DRYADBARK = "#37352f",
    WHITE = "#ffffff",
    ERRIGAL_WHITE = "#f6f6f9",
    GAINSBORO = "#d9d9d9",
    CORAL_RED = "#f93e3d",
    TRANSLUCENT_UNICORN = "#fcecee",
    SOFT_PETALS = "#e9f6ef",
    VEGETATION = "#48cd90",
    STONEWALL_GREY = "#c3c2c1",
    ASTROGRANITE_DEBRIS = "#3b414a",
    ASWAD_BLACK = "#141519",
    WASHED_BLACK = "#202528",
    DARK_VIOLET = "#6a0dad",
    LIGHT_VIOLET = "#9b59b6",
    MEDIUM_VIOLET = "#8e44ad",
    SOFT_VIOLET = "#d2a6e6",
}